name: Test
on: [push]

jobs:
  build:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      # Run the install script
      - name: Run script
        run: ./bootstrap.sh