name: Test
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Test
    # This job runs on Linux
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      # Run the install script
      - name: Verify path & contents
        run: pwd && ls -la